function getDefaultOpts(a){var c={omitExtraWLInCodeBlocks:{defaultValue:!1,describe:"Omit the default extra whiteline added to code blocks",type:"boolean"},noHeaderId:{defaultValue:!1,describe:"Turn on/off generated header id",type:"boolean"},prefixHeaderId:{defaultValue:!1,describe:"Specify a prefix to generated header ids",type:"string"},headerLevelStart:{defaultValue:!1,describe:"The header blocks level start",type:"integer"},parseImgDimensions:{defaultValue:!1,describe:"Turn on/off image dimension parsing",
type:"boolean"},simplifiedAutoLink:{defaultValue:!1,describe:"Turn on/off GFM autolink style",type:"boolean"},literalMidWordUnderscores:{defaultValue:!1,describe:"Parse midword underscores as literal underscores",type:"boolean"},strikethrough:{defaultValue:!1,describe:"Turn on/off strikethrough support",type:"boolean"},tables:{defaultValue:!1,describe:"Turn on/off tables support",type:"boolean"},tablesHeaderId:{defaultValue:!1,describe:"Add an id to table headers",type:"boolean"},ghCodeBlocks:{defaultValue:!0,
describe:"Turn on/off GFM fenced code blocks support",type:"boolean"},tasklists:{defaultValue:!1,describe:"Turn on/off GFM tasklist support",type:"boolean"},smoothLivePreview:{defaultValue:!1,describe:"Prevents weird effects in live previews due to incomplete input",type:"boolean"},smartIndentationFix:{defaultValue:!1,description:"Tries to smartly fix identation in es6 strings",type:"boolean"}};if(!1===a)return JSON.parse(JSON.stringify(c));a={};for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b].defaultValue);
return a}var showdown={},parsers={},extensions={},globalOptions=getDefaultOpts(!0),flavor={github:{omitExtraWLInCodeBlocks:!0,prefixHeaderId:"user-content-",simplifiedAutoLink:!0,literalMidWordUnderscores:!0,strikethrough:!0,tables:!0,tablesHeaderId:!0,ghCodeBlocks:!0,tasklists:!0},vanilla:getDefaultOpts(!0)};showdown.helper={};showdown.extensions={};showdown.setOption=function(a,c){globalOptions[a]=c;return this};showdown.getOption=function(a){return globalOptions[a]};showdown.getOptions=function(){return globalOptions};
showdown.resetOptions=function(){globalOptions=getDefaultOpts(!0)};showdown.setFlavor=function(a){if(flavor.hasOwnProperty(a)){a=flavor[a];for(var c in a)a.hasOwnProperty(c)&&(globalOptions[c]=a[c])}};showdown.getDefaultOptions=function(a){return getDefaultOpts(a)};showdown.subParser=function(a,c){if(showdown.helper.isString(a))if("undefined"!==typeof c)parsers[a]=c;else{if(parsers.hasOwnProperty(a))return parsers[a];throw Error("SubParser named "+a+" not registered!");}};
showdown.extension=function(a,c){if(!showdown.helper.isString(a))throw Error("Extension 'name' must be a string");a=showdown.helper.stdExtName(a);if(showdown.helper.isUndefined(c)){if(!extensions.hasOwnProperty(a))throw Error("Extension named "+a+" is not registered!");return extensions[a]}"function"===typeof c&&(c=c());showdown.helper.isArray(c)||(c=[c]);var b=validate(c,a);if(b.valid)extensions[a]=c;else throw Error(b.error);};showdown.getAllExtensions=function(){return extensions};
showdown.removeExtension=function(a){delete extensions[a]};showdown.resetExtensions=function(){extensions={}};
function validate(a,c){c=c?"Error in "+c+" extension->":"Error in unnamed extension";var b={valid:!0,error:""};showdown.helper.isArray(a)||(a=[a]);for(var f=0;f<a.length;++f){var e=c+" sub-extension "+f+": ",d=a[f];if("object"!==typeof d){b.valid=!1;b.error=e+"must be an object, but "+typeof d+" given";break}if(!showdown.helper.isString(d.type)){b.valid=!1;b.error=e+'property "type" must be a string, but '+typeof d.type+" given";break}var g=d.type=d.type.toLowerCase();"language"===g&&(g=d.type="lang");
"html"===g&&(g=d.type="output");if("lang"!==g&&"output"!==g&&"listener"!==g){b.valid=!1;b.error=e+"type "+g+' is not recognized. Valid values: "lang/language", "output/html" or "listener"';break}if("listener"===g){if(showdown.helper.isUndefined(d.listeners)){b.valid=!1;b.error=e+'. Extensions of type "listener" must have a property called "listeners"';break}}else if(showdown.helper.isUndefined(d.filter)&&showdown.helper.isUndefined(d.regex)){b.valid=!1;b.error=e+g+' extensions must define either a "regex" property or a "filter" method';
break}if(d.listeners){if("object"!==typeof d.listeners){b.valid=!1;b.error=e+'"listeners" property must be an object but '+typeof d.listeners+" given";break}for(var k in d.listeners)if(d.listeners.hasOwnProperty(k)&&"function"!==typeof d.listeners[k])return b.valid=!1,b.error=e+'"listeners" property must be an hash of [event name]: [callback]. listeners.'+k+" must be a function but "+typeof d.listeners[k]+" given",b}if(d.filter){if("function"!==typeof d.filter){b.valid=!1;b.error=e+'"filter" must be a function, but '+
typeof d.filter+" given";break}}else if(d.regex){showdown.helper.isString(d.regex)&&(d.regex=new RegExp(d.regex,"g"));if(!d.regex instanceof RegExp){b.valid=!1;b.error=e+'"regex" property must either be a string or a RegExp object, but '+typeof d.regex+" given";break}if(showdown.helper.isUndefined(d.replace)){b.valid=!1;b.error=e+'"regex" extensions must implement a replace string or function';break}}}return b}
showdown.validateExtension=function(a){a=validate(a,null);return a.valid?!0:(console.warn(a.error),!1)};showdown.hasOwnProperty("helper")||(showdown.helper={});showdown.helper.isString=function(a){return"string"===typeof a||a instanceof String};showdown.helper.isFunction=function(a){var c={};return a&&"[object Function]"===c.toString.call(a)};showdown.helper.forEach=function(a,c){if("function"===typeof a.forEach)a.forEach(c);else for(var b=0;b<a.length;b++)c(a[b],b,a)};
showdown.helper.isArray=function(a){return a.constructor===Array};showdown.helper.isUndefined=function(a){return"undefined"===typeof a};showdown.helper.stdExtName=function(a){return a.replace(/[_-]||\s/g,"").toLowerCase()};function escapeCharactersCallback(a,c){return"~E"+c.charCodeAt(0)+"E"}showdown.helper.escapeCharactersCallback=escapeCharactersCallback;
showdown.helper.escapeCharacters=function(a,c,b){c="(["+c.replace(/([\[\]\\])/g,"\\$1")+"])";b&&(c="\\\\"+c);return a=a.replace(new RegExp(c,"g"),escapeCharactersCallback)};
var rgxFindMatchPos=function(a,c,b,f){var e=f||"";f=-1<e.indexOf("g");b=new RegExp(c+"|"+b,"g"+e.replace(/g/g,""));c=new RegExp(c,e.replace(/g/g,""));e=[];var d,g;do for(d=0;g=b.exec(a);)if(c.test(g[0])){if(!d++){var k=b.lastIndex;var h=k-g[0].length}}else if(d&&!--d){var m=g.index+g[0].length;e.push({left:{start:h,end:k},match:{start:k,end:g.index},right:{start:g.index,end:m},wholeMatch:{start:h,end:m}});if(!f)return e}while(d&&(b.lastIndex=k));return e};
showdown.helper.matchRecursiveRegExp=function(a,c,b,f){c=rgxFindMatchPos(a,c,b,f);b=[];for(f=0;f<c.length;++f)b.push([a.slice(c[f].wholeMatch.start,c[f].wholeMatch.end),a.slice(c[f].match.start,c[f].match.end),a.slice(c[f].left.start,c[f].left.end),a.slice(c[f].right.start,c[f].right.end)]);return b};
showdown.helper.replaceRecursiveRegExp=function(a,c,b,f,e){if(!showdown.helper.isFunction(c)){var d=c;c=function(){return d}}b=rgxFindMatchPos(a,b,f,e);e=a;f=b.length;if(0<f){e=[];0!==b[0].wholeMatch.start&&e.push(a.slice(0,b[0].wholeMatch.start));for(var g=0;g<f;++g)e.push(c(a.slice(b[g].wholeMatch.start,b[g].wholeMatch.end),a.slice(b[g].match.start,b[g].match.end),a.slice(b[g].left.start,b[g].left.end),a.slice(b[g].right.start,b[g].right.end))),g<f-1&&e.push(a.slice(b[g].wholeMatch.end,b[g+1].wholeMatch.start));
b[f-1].wholeMatch.end<a.length&&e.push(a.slice(b[f-1].wholeMatch.end));e=e.join("")}return e};showdown.helper.isUndefined(console)&&(console={warn:function(a){alert(a)},log:function(a){alert(a)},error:function(a){throw a;}});
showdown.Converter=function(a){function c(a,c){c=c||null;if(showdown.helper.isString(a)){c=a=showdown.helper.stdExtName(a);if(showdown.extensions[a]){console.warn("DEPRECATION WARNING: "+a+" is an old extension that uses a deprecated loading method.Please inform the developer that the extension should be updated!");var h=showdown.extensions[a];"function"===typeof h&&(h=h(new showdown.Converter));showdown.helper.isArray(h)||(h=[h]);a=validate(h,a);if(!a.valid)throw Error(a.error);for(a=0;a<h.length;++a)switch(h[a].type){case "lang":d.push(h[a]);
break;case "output":g.push(h[a]);break;default:throw Error("Extension loader error: Type unrecognized!!!");}return}if(showdown.helper.isUndefined(extensions[a]))throw Error('Extension "'+a+'" could not be loaded. It was either not found or is not a valid extension.');a=extensions[a]}"function"===typeof a&&(a=a());showdown.helper.isArray(a)||(a=[a]);c=validate(a,c);if(!c.valid)throw Error(c.error);for(c=0;c<a.length;++c){switch(a[c].type){case "lang":d.push(a[c]);break;case "output":g.push(a[c])}if(a[c].hasOwnProperty(k))for(h in a[c].listeners)a[c].listeners.hasOwnProperty(h)&&
b(h,a[c].listeners[h])}}function b(a,b){if(!showdown.helper.isString(a))throw Error("Invalid argument in converter.listen() method: name must be a string, but "+typeof a+" given");if("function"!==typeof b)throw Error("Invalid argument in converter.listen() method: callback must be a function, but "+typeof b+" given");k.hasOwnProperty(a)||(k[a]=[]);k[a].push(b)}function f(a){var b=a.match(/^\s*/)[0].length;return a.replace(new RegExp("^\\s{0,"+b+"}","gm"),"")}var e={},d=[],g=[],k={};(function(){a=
a||{};for(var b in globalOptions)globalOptions.hasOwnProperty(b)&&(e[b]=globalOptions[b]);if("object"===typeof a)for(var f in a)a.hasOwnProperty(f)&&(e[f]=a[f]);else throw Error("Converter expects the passed parameter to be an object, but "+typeof a+" was passed instead.");e.extensions&&showdown.helper.forEach(e.extensions,c)})();this._dispatch=function(a,b,c,f){if(k.hasOwnProperty(a))for(var h=0;h<k[a].length;++h){var d=k[a][h](a,b,this,c,f);d&&"undefined"!==typeof d&&(b=d)}return b};this.listen=
function(a,c){b(a,c);return this};this.makeHtml=function(a){if(!a)return a;var b={gHtmlBlocks:[],gHtmlMdBlocks:[],gHtmlSpans:[],gUrls:{},gTitles:{},gDimensions:{},gListLevel:0,hashLinkCounts:{},langExtensions:d,outputModifiers:g,converter:this,ghCodeBlocks:[]};a=a.replace(/~/g,"~T");a=a.replace(/\$/g,"~D");a=a.replace(/\r\n/g,"\n");a=a.replace(/\r/g,"\n");e.smartIndentationFix&&(a=f(a));a=showdown.subParser("detab")(a,e,b);a=showdown.subParser("stripBlankLines")(a,e,b);showdown.helper.forEach(d,function(c){a=
showdown.subParser("runExtension")(c,a,e,b)});a=showdown.subParser("hashPreCodeTags")(a,e,b);a=showdown.subParser("githubCodeBlocks")(a,e,b);a=showdown.subParser("hashHTMLBlocks")(a,e,b);a=showdown.subParser("hashHTMLSpans")(a,e,b);a=showdown.subParser("stripLinkDefinitions")(a,e,b);a=showdown.subParser("blockGamut")(a,e,b);a=showdown.subParser("unhashHTMLSpans")(a,e,b);a=showdown.subParser("unescapeSpecialChars")(a,e,b);a=a.replace(/~D/g,"$$");a=a.replace(/~T/g,"~");showdown.helper.forEach(g,function(c){a=
showdown.subParser("runExtension")(c,a,e,b)});return a};this.setOption=function(a,b){e[a]=b};this.getOption=function(a){return e[a]};this.getOptions=function(){return e};this.addExtension=function(a,b){c(a,b||null)};this.useExtension=function(a){c(a)};this.setFlavor=function(a){if(flavor.hasOwnProperty(a)){a=flavor[a];for(var b in a)a.hasOwnProperty(b)&&(e[b]=a[b])}};this.removeExtension=function(a){showdown.helper.isArray(a)||(a=[a]);for(var b=0;b<a.length;++b){for(var c=a[b],f=0;f<d.length;++f)d[f]===
c&&d[f].splice(f,1);for(;0<g.length;++f)g[0]===c&&g[0].splice(f,1)}};this.getAllExtensions=function(){return{language:d,output:g}}};
showdown.subParser("anchors",function(a,c,b){a=b.converter._dispatch("anchors.before",a,c,b);var f=function(a,c,f,k,h,m,q,l){showdown.helper.isUndefined(l)&&(l="");a=c;c=k.toLowerCase();if(!h)if(c||(c=f.toLowerCase().replace(/ ?\n/g," ")),showdown.helper.isUndefined(b.gUrls[c]))if(-1<a.search(/\(\s*\)$/m))h="";else return a;else h=b.gUrls[c],showdown.helper.isUndefined(b.gTitles[c])||(l=b.gTitles[c]);h=showdown.helper.escapeCharacters(h,"*_",!1);a='<a href="'+h+'"';""!==l&&null!==l&&(l=l.replace(/"/g,
"&quot;"),l=showdown.helper.escapeCharacters(l,"*_",!1),a+=' title="'+l+'"');return a+(">"+f+"</a>")};a=a.replace(/(\[((?:\[[^\]]*]|[^\[\]])*)][ ]?(?:\n[ ]*)?\[(.*?)])()()()()/g,f);a=a.replace(/(\[((?:\[[^\]]*]|[^\[\]])*)]\([ \t]*()<?(.*?(?:\(.*?\).*?)?)>?[ \t]*((['"])(.*?)\6[ \t]*)?\))/g,f);a=a.replace(/(\[([^\[\]]+)])()()()()()/g,f);return a=b.converter._dispatch("anchors.after",a,c,b)});
showdown.subParser("autoLinks",function(a,c,b){function f(a,b){a=b;/^www\./i.test(b)&&(b=b.replace(/^www\./i,"http://www."));return'<a href="'+b+'">'+a+"</a>"}function e(a,b){a=showdown.subParser("unescapeSpecialChars")(b);return showdown.subParser("encodeEmailAddress")(a)}a=b.converter._dispatch("autoLinks.before",a,c,b);var d=/\b(((https?|ftp|dict):\/\/|www\.)[^'">\s]+\.[^'">\s]+)(?=\s|$)(?!["<>])/gi,g=/(?:^|[ \n\t])([A-Za-z0-9!#$%&'*+-/=?^_`\{|}~\.]+@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)(?:$|[ \n\t])/gi;
a=a.replace(/<(((https?|ftp|dict):\/\/|www\.)[^'">\s]+)>/gi,f);a=a.replace(/<(?:mailto:)?([-.\w]+@[-a-z0-9]+(\.[-a-z0-9]+)*\.[a-z]+)>/gi,e);c.simplifiedAutoLink&&(a=a.replace(d,f),a=a.replace(g,e));return a=b.converter._dispatch("autoLinks.after",a,c,b)});
showdown.subParser("blockGamut",function(a,c,b){a=b.converter._dispatch("blockGamut.before",a,c,b);a=showdown.subParser("blockQuotes")(a,c,b);a=showdown.subParser("headers")(a,c,b);var f=showdown.subParser("hashBlock")("<hr />",c,b);a=a.replace(/^[ ]{0,2}([ ]?\*[ ]?){3,}[ \t]*$/gm,f);a=a.replace(/^[ ]{0,2}([ ]?\-[ ]?){3,}[ \t]*$/gm,f);a=a.replace(/^[ ]{0,2}([ ]?_[ ]?){3,}[ \t]*$/gm,f);a=showdown.subParser("lists")(a,c,b);a=showdown.subParser("codeBlocks")(a,c,b);a=showdown.subParser("tables")(a,c,
b);a=showdown.subParser("hashHTMLBlocks")(a,c,b);a=showdown.subParser("paragraphs")(a,c,b);return a=b.converter._dispatch("blockGamut.after",a,c,b)});
showdown.subParser("blockQuotes",function(a,c,b){a=b.converter._dispatch("blockQuotes.before",a,c,b);a=a.replace(/((^[ \t]{0,3}>[ \t]?.+\n(.+\n)*\n*)+)/gm,function(a,e){a=e.replace(/^[ \t]*>[ \t]?/gm,"~0");a=a.replace(/~0/g,"");a=a.replace(/^[ \t]+$/gm,"");a=showdown.subParser("githubCodeBlocks")(a,c,b);a=showdown.subParser("blockGamut")(a,c,b);a=a.replace(/(^|\n)/g,"$1  ");a=a.replace(/(\s*<pre>[^\r]+?<\/pre>)/gm,function(a,b){a=b.replace(/^  /mg,"~0");return a=a.replace(/~0/g,"")});return showdown.subParser("hashBlock")("<blockquote>\n"+
a+"\n</blockquote>",c,b)});return a=b.converter._dispatch("blockQuotes.after",a,c,b)});
showdown.subParser("codeBlocks",function(a,c,b){a=b.converter._dispatch("codeBlocks.before",a,c,b);a=(a+"~0").replace(/(?:\n\n|^)((?:(?:[ ]{4}|\t).*\n+)+)(\n*[ ]{0,3}[^ \t\n]|(?=~0))/g,function(a,e,d){a=e;e="\n";a=showdown.subParser("outdent")(a);a=showdown.subParser("encodeCode")(a);a=showdown.subParser("detab")(a);a=a.replace(/^\n+/g,"");a=a.replace(/\n+$/g,"");c.omitExtraWLInCodeBlocks&&(e="");a="<pre><code>"+a+e+"</code></pre>";return showdown.subParser("hashBlock")(a,c,b)+d});a=a.replace(/~0/,
"");return a=b.converter._dispatch("codeBlocks.after",a,c,b)});showdown.subParser("codeSpans",function(a,c,b){a=b.converter._dispatch("codeSpans.before",a,c,b);"undefined"===typeof a&&(a="");a=a.replace(/(^|[^\\])(`+)([^\r]*?[^`])\2(?!`)/gm,function(a,b,c,g){a=g.replace(/^([ \t]*)/g,"");a=a.replace(/[ \t]*$/g,"");a=showdown.subParser("encodeCode")(a);return b+"<code>"+a+"</code>"});return a=b.converter._dispatch("codeSpans.after",a,c,b)});
showdown.subParser("detab",function(a){a=a.replace(/\t(?=\t)/g,"    ");a=a.replace(/\t/g,"~A~B");a=a.replace(/~B(.+?)~A/g,function(a,b){a=b;b=4-a.length%4;for(var c=0;c<b;c++)a+=" ";return a});a=a.replace(/~A/g,"    ");return a=a.replace(/~B/g,"")});showdown.subParser("encodeAmpsAndAngles",function(a){a=a.replace(/&(?!#?[xX]?(?:[0-9a-fA-F]+|\w+);)/g,"&amp;");return a=a.replace(/<(?![a-z\/?\$!])/gi,"&lt;")});
showdown.subParser("encodeBackslashEscapes",function(a){a=a.replace(/\\(\\)/g,showdown.helper.escapeCharactersCallback);return a=a.replace(/\\([`*_{}\[\]()>#+-.!])/g,showdown.helper.escapeCharactersCallback)});showdown.subParser("encodeCode",function(a){a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");return a=showdown.helper.escapeCharacters(a,"*_{}[]\\",!1)});
showdown.subParser("encodeEmailAddress",function(a){var c=[function(a){return"&#"+a.charCodeAt(0)+";"},function(a){return"&#x"+a.charCodeAt(0).toString(16)+";"},function(a){return a}];a=("mailto:"+a).replace(/./g,function(a){if("@"===a)a=c[Math.floor(2*Math.random())](a);else if(":"!==a){var b=Math.random();a=.9<b?c[2](a):.45<b?c[1](a):c[0](a)}return a});return a=('<a href="'+a+'">'+a+"</a>").replace(/">.+:/g,'">')});
showdown.subParser("escapeSpecialCharsWithinTagAttributes",function(a){return a=a.replace(/(<[a-z\/!$]("[^"]*"|'[^']*'|[^'">])*>|<!(--.*?--\s*)+>)/gi,function(a){a=a.replace(/(.)<\/?code>(?=.)/g,"$1`");return a=showdown.helper.escapeCharacters(a,"\\`*_",!1)})});
showdown.subParser("githubCodeBlocks",function(a,c,b){if(!c.ghCodeBlocks)return a;a=b.converter._dispatch("githubCodeBlocks.before",a,c,b);a=(a+"~0").replace(/(?:^|\n)```(.*)\n([\s\S]*?)\n```/g,function(a,e,d){var g=c.omitExtraWLInCodeBlocks?"":"\n";d=showdown.subParser("encodeCode")(d);d=showdown.subParser("detab")(d);d=d.replace(/^\n+/g,"");d=d.replace(/\n+$/g,"");d="<pre><code"+(e?' class="'+e+" language-"+e+'"':"")+">"+d+g+"</code></pre>";d=showdown.subParser("hashBlock")(d,c,b);return"\n\n~G"+
(b.ghCodeBlocks.push({text:a,codeblock:d})-1)+"G\n\n"});a=a.replace(/~0/,"");return b.converter._dispatch("githubCodeBlocks.after",a,c,b)});showdown.subParser("hashBlock",function(a,c,b){a=a.replace(/(^\n+|\n+$)/g,"");return"\n\n~K"+(b.gHtmlBlocks.push(a)-1)+"K\n\n"});showdown.subParser("hashElement",function(a,c,b){return function(a,c){a=c.replace(/\n\n/g,"\n");a=a.replace(/^\n/,"");a=a.replace(/\n+$/g,"");return a="\n\n~K"+(b.gHtmlBlocks.push(a)-1)+"K\n\n"}});
showdown.subParser("hashHTMLBlocks",function(a,c,b){for(var f="pre div h1 h2 h3 h4 h5 h6 blockquote table dl ol ul script noscript form fieldset iframe math style section header footer nav article aside address audio canvas figure hgroup output video p".split(" "),e=function(a,c,h,d){-1!==h.search(/\bmarkdown\b/)&&(a=h+b.converter.makeHtml(c)+d);return"\n\n~K"+(b.gHtmlBlocks.push(a)-1)+"K\n\n"},d=0;d<f.length;++d)a=showdown.helper.replaceRecursiveRegExp(a,e,"^(?: |\\t){0,3}<"+f[d]+"\\b[^>]*>","</"+
f[d]+">","gim");a=a.replace(/(\n[ ]{0,3}(<(hr)\b([^<>])*?\/?>)[ \t]*(?=\n{2,}))/g,showdown.subParser("hashElement")(a,c,b));a=a.replace(/(\x3c!--[\s\S]*?--\x3e)/g,showdown.subParser("hashElement")(a,c,b));return a=a.replace(/(?:\n\n)([ ]{0,3}(?:<([?%])[^\r]*?\2>)[ \t]*(?=\n{2,}))/g,showdown.subParser("hashElement")(a,c,b))});
showdown.subParser("hashHTMLSpans",function(a,c,b){c=showdown.helper.matchRecursiveRegExp(a,"<code\\b[^>]*>","</code>","gi");for(var f=0;f<c.length;++f)a=a.replace(c[f][0],"~L"+(b.gHtmlSpans.push(c[f][0])-1)+"L");return a});showdown.subParser("unhashHTMLSpans",function(a,c,b){for(c=0;c<b.gHtmlSpans.length;++c)a=a.replace("~L"+c+"L",b.gHtmlSpans[c]);return a});
showdown.subParser("hashPreCodeTags",function(a,c,b){return a=showdown.helper.replaceRecursiveRegExp(a,function(a,c,d,g){c=d+showdown.subParser("encodeCode")(c)+g;return"\n\n~G"+(b.ghCodeBlocks.push({text:a,codeblock:c})-1)+"G\n\n"},"^(?: |\\t){0,3}<pre\\b[^>]*>\\s*<code\\b[^>]*>","^(?: |\\t){0,3}</code>\\s*</pre>","gim")});
showdown.subParser("headers",function(a,c,b){function f(a){var c=a.replace(/[^\w]/g,"").toLowerCase();b.hashLinkCounts[c]?a=c+"-"+b.hashLinkCounts[c]++:(a=c,b.hashLinkCounts[c]=1);!0===e&&(e="section");return showdown.helper.isString(e)?e+a:a}a=b.converter._dispatch("headers.before",a,c,b);var e=c.prefixHeaderId,d=isNaN(parseInt(c.headerLevelStart))?1:parseInt(c.headerLevelStart),g=c.smoothLivePreview?/^(.+)[ \t]*\n-{2,}[ \t]*\n+/gm:/^(.+)[ \t]*\n-+[ \t]*\n+/gm;a=a.replace(c.smoothLivePreview?/^(.+)[ \t]*\n={2,}[ \t]*\n+/gm:
/^(.+)[ \t]*\n=+[ \t]*\n+/gm,function(a,h){a=showdown.subParser("spanGamut")(h,c,b);h=c.noHeaderId?"":' id="'+f(h)+'"';h="<h"+d+h+">"+a+"</h"+d+">";return showdown.subParser("hashBlock")(h,c,b)});a=a.replace(g,function(a,h){a=showdown.subParser("spanGamut")(h,c,b);h=c.noHeaderId?"":' id="'+f(h)+'"';var g=d+1;a="<h"+g+h+">"+a+"</h"+g+">";return showdown.subParser("hashBlock")(a,c,b)});a=a.replace(/^(#{1,6})[ \t]*(.+?)[ \t]*#*\n+/gm,function(a,g,e){a=showdown.subParser("spanGamut")(e,c,b);e=c.noHeaderId?
"":' id="'+f(e)+'"';g=d-1+g.length;g="<h"+g+e+">"+a+"</h"+g+">";return showdown.subParser("hashBlock")(g,c,b)});return a=b.converter._dispatch("headers.after",a,c,b)});
showdown.subParser("images",function(a,c,b){function f(a,c,g,f,h,m,q,l){q=b.gUrls;var d=b.gTitles,e=b.gDimensions;g=g.toLowerCase();l||(l="");if(""===f||null===f){if(""===g||null===g)g=c.toLowerCase().replace(/ ?\n/g," ");if(showdown.helper.isUndefined(q[g]))return a;f=q[g];showdown.helper.isUndefined(d[g])||(l=d[g]);showdown.helper.isUndefined(e[g])||(h=e[g].width,m=e[g].height)}c=c.replace(/"/g,"&quot;");c=showdown.helper.escapeCharacters(c,"*_",!1);f=showdown.helper.escapeCharacters(f,"*_",!1);
a='<img src="'+f+'" alt="'+c+'"';l&&(l=l.replace(/"/g,"&quot;"),l=showdown.helper.escapeCharacters(l,"*_",!1),a+=' title="'+l+'"');h&&m&&(a=a+(' width="'+("*"===h?"auto":h)+'"')+(' height="'+("*"===m?"auto":m)+'"'));return a+" />"}a=b.converter._dispatch("images.before",a,c,b);a=a.replace(/!\[([^\]]*?)] ?(?:\n *)?\[(.*?)]()()()()()/g,f);a=a.replace(/!\[(.*?)]\s?\([ \t]*()<?(\S+?)>?(?: =([*\d]+[A-Za-z%]{0,4})x([*\d]+[A-Za-z%]{0,4}))?[ \t]*(?:(['"])(.*?)\6[ \t]*)?\)/g,f);return a=b.converter._dispatch("images.after",
a,c,b)});
showdown.subParser("italicsAndBold",function(a,c,b){a=b.converter._dispatch("italicsAndBold.before",a,c,b);c.literalMidWordUnderscores?(a=a.replace(/(^|\s|>|\b)__(?=\S)([\s\S]+?)__(?=\b|<|\s|$)/gm,"$1<strong>$2</strong>"),a=a.replace(/(^|\s|>|\b)_(?=\S)([\s\S]+?)_(?=\b|<|\s|$)/gm,"$1<em>$2</em>"),a=a.replace(/(\*\*)(?=\S)([^\r]*?\S[*]*)\1/g,"<strong>$2</strong>"),a=a.replace(/(\*)(?=\S)([^\r]*?\S)\1/g,"<em>$2</em>")):(a=a.replace(/(\*\*|__)(?=\S)([^\r]*?\S[*_]*)\1/g,"<strong>$2</strong>"),a=a.replace(/(\*|_)(?=\S)([^\r]*?\S)\1/g,
"<em>$2</em>"));return a=b.converter._dispatch("italicsAndBold.after",a,c,b)});
showdown.subParser("lists",function(a,c,b){function f(a,d){b.gListLevel++;a=a.replace(/\n{2,}$/,"\n");a+="~0";var g=/\n[ \t]*\n(?!~0)/.test(a);a=a.replace(/(\n)?(^[ \t]*)([*+-]|\d+[.])[ \t]+((\[(x|X| )?])?[ \t]*[^\r]+?(\n{1,2}))(?=\n*(~0|\2([*+-]|\d+[.])[ \t]+))/gm,function(a,d,f,h,e,k,p){p=p&&""!==p.trim();a=showdown.subParser("outdent")(e,c,b);f="";k&&c.tasklists&&(f=' class="task-list-item" style="list-style-type: none;"',a=a.replace(/^[ \t]*\[(x|X| )?]/m,function(){var a='<input type="checkbox" disabled style="margin: 0px 0.35em 0.25em -1.6em; vertical-align: middle;"';
p&&(a+=" checked");return a+">"}));d||-1<a.search(/\n{2,}/)?(a=showdown.subParser("githubCodeBlocks")(a,c,b),a=showdown.subParser("blockGamut")(a,c,b)):(a=showdown.subParser("lists")(a,c,b),a=a.replace(/\n$/,""),a=g?showdown.subParser("paragraphs")(a,c,b):showdown.subParser("spanGamut")(a,c,b));return"\n<li"+f+">"+a+"</li>\n"});a=a.replace(/~0/g,"");b.gListLevel--;d&&(a=a.replace(/\s+$/,""));return a}function e(a,b,c){var d="ul"===b?/^ {0,2}\d+\.[ \t]/gm:/^ {0,2}[*+-][ \t]/gm,e=[],g="";if(-1!==a.search(d))for(function n(a){var e=
a.search(d);-1!==e?(g+="\n\n<"+b+">"+f(a.slice(0,e),!!c)+"</"+b+">\n\n",b="ul"===b?"ol":"ul",d="ul"===b?/^ {0,2}\d+\.[ \t]/gm:/^ {0,2}[*+-][ \t]/gm,n(a.slice(e))):g+="\n\n<"+b+">"+f(a,!!c)+"</"+b+">\n\n"}(a),a=0;a<e.length;++a);else g="\n\n<"+b+">"+f(a,!!c)+"</"+b+">\n\n";return g}a=b.converter._dispatch("lists.before",a,c,b);a+="~0";var d=/^(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm;b.gListLevel?a=a.replace(d,function(a,b,c){a=-1<c.search(/[*+-]/g)?
"ul":"ol";return e(b,a,!0)}):(d=/(\n\n|^\n?)(([ ]{0,3}([*+-]|\d+[.])[ \t]+)[^\r]+?(~0|\n{2,}(?=\S)(?![ \t]*(?:[*+-]|\d+[.])[ \t]+)))/gm,a=a.replace(d,function(a,b,c,d){a=-1<d.search(/[*+-]/g)?"ul":"ol";return e(c,a)}));a=a.replace(/~0/,"");return a=b.converter._dispatch("lists.after",a,c,b)});showdown.subParser("outdent",function(a){a=a.replace(/^(\t|[ ]{1,4})/gm,"~0");return a=a.replace(/~0/g,"")});
showdown.subParser("paragraphs",function(a,c,b){a=b.converter._dispatch("paragraphs.before",a,c,b);a=a.replace(/^\n+/g,"");a=a.replace(/\n+$/g,"");var f=a.split(/\n{2,}/g);a=[];for(var e=f.length,d=0;d<e;d++){var g=f[d];0<=g.search(/~(K|G)(\d+)\1/g)||(g=showdown.subParser("spanGamut")(g,c,b),g=g.replace(/^([ \t]*)/g,"<p>"),g+="</p>");a.push(g)}e=a.length;for(d=0;d<e;d++){f=a[d];for(g=!1;0<=f.search(/~(K|G)(\d+)\1/);){var k=RegExp.$2;k="K"===RegExp.$1?b.gHtmlBlocks[k]:g?showdown.subParser("encodeCode")(b.ghCodeBlocks[k].text):
b.ghCodeBlocks[k].codeblock;k=k.replace(/\$/g,"$$$$");f=f.replace(/(\n\n)?~(K|G)\d+\2(\n\n)?/,k);/^<pre\b[^>]*>\s*<code\b[^>]*>/.test(f)&&(g=!0)}a[d]=f}a=a.join("\n\n");a=a.replace(/^\n+/g,"");a=a.replace(/\n+$/g,"");return b.converter._dispatch("paragraphs.after",a,c,b)});showdown.subParser("runExtension",function(a,c,b,f){a.filter?c=a.filter(c,f.converter,b):a.regex&&(b=a.regex,!b instanceof RegExp&&(b=new RegExp(b,"g")),c=c.replace(b,a.replace));return c});
showdown.subParser("spanGamut",function(a,c,b){a=b.converter._dispatch("spanGamut.before",a,c,b);a=showdown.subParser("codeSpans")(a,c,b);a=showdown.subParser("escapeSpecialCharsWithinTagAttributes")(a,c,b);a=showdown.subParser("encodeBackslashEscapes")(a,c,b);a=showdown.subParser("images")(a,c,b);a=showdown.subParser("anchors")(a,c,b);a=showdown.subParser("autoLinks")(a,c,b);a=showdown.subParser("encodeAmpsAndAngles")(a,c,b);a=showdown.subParser("italicsAndBold")(a,c,b);a=showdown.subParser("strikethrough")(a,
c,b);a=a.replace(/  +\n/g," <br />\n");return a=b.converter._dispatch("spanGamut.after",a,c,b)});showdown.subParser("strikethrough",function(a,c,b){c.strikethrough&&(a=b.converter._dispatch("strikethrough.before",a,c,b),a=a.replace(/(?:~T){2}([\s\S]+?)(?:~T){2}/g,"<del>$1</del>"),a=b.converter._dispatch("strikethrough.after",a,c,b));return a});showdown.subParser("stripBlankLines",function(a){return a.replace(/^[ \t]+$/mg,"")});
showdown.subParser("stripLinkDefinitions",function(a,c,b){a=(a+"~0").replace(/^ {0,3}\[(.+)]:[ \t]*\n?[ \t]*<?(\S+?)>?(?: =([*\d]+[A-Za-z%]{0,4})x([*\d]+[A-Za-z%]{0,4}))?[ \t]*\n?[ \t]*(?:(\n*)["|'(](.+?)["|')][ \t]*)?(?:\n+|(?=~0))/gm,function(a,e,d,g,k,h,m){e=e.toLowerCase();b.gUrls[e]=showdown.subParser("encodeAmpsAndAngles")(d);if(h)return h+m;m&&(b.gTitles[e]=m.replace(/"|'/g,"&quot;"));c.parseImgDimensions&&g&&k&&(b.gDimensions[e]={width:g,height:k});return""});return a=a.replace(/~0/,"")});
showdown.subParser("tables",function(a,c,b){function f(a){return/^:[ \t]*--*$/.test(a)?' style="text-align:left;"':/^--*[ \t]*:[ \t]*$/.test(a)?' style="text-align:right;"':/^:[ \t]*--*[ \t]*:$/.test(a)?' style="text-align:center;"':""}function e(a,d){var e="";a=a.trim();c.tableHeaderId&&(e=' id="'+a.replace(/ /g,"_").toLowerCase()+'"');a=showdown.subParser("spanGamut")(a,c,b);return"<th"+e+d+">"+a+"</th>\n"}function d(a,d){a=showdown.subParser("spanGamut")(a,c,b);return"<td"+d+">"+a+"</td>\n"}function g(a,
b){for(var c="<table>\n<thead>\n<tr>\n",d=a.length,e=0;e<d;++e)c+=a[e];c+="</tr>\n</thead>\n<tbody>\n";for(e=0;e<b.length;++e){c+="<tr>\n";for(a=0;a<d;++a)c+=b[e][a];c+="</tr>\n"}return c+"</tbody>\n</table>\n"}if(!c.tables)return a;a=b.converter._dispatch("tables.before",a,c,b);a=a.replace(/^[ \t]{0,3}\|?.+\|.+\n[ \t]{0,3}\|?[ \t]*:?[ \t]*(?:-|=){2,}[ \t]*:?[ \t]*\|[ \t]*:?[ \t]*(?:-|=){2,}[\s\S]+?(?:\n\n|~0)/gm,function(a){var b,c=a.split("\n");for(b=0;b<c.length;++b)/^[ \t]{0,3}\|/.test(c[b])&&
(c[b]=c[b].replace(/^[ \t]{0,3}\|/,"")),/\|[ \t]*$/.test(c[b])&&(c[b]=c[b].replace(/\|[ \t]*$/,""));var k=c[0].split("|").map(function(a){return a.trim()}),l=c[1].split("|").map(function(a){return a.trim()}),r=[],t=[],n=[],p=[];c.shift();c.shift();for(b=0;b<c.length;++b)""!==c[b].trim()&&r.push(c[b].split("|").map(function(a){return a.trim()}));if(k.length<l.length)return a;for(b=0;b<l.length;++b)n.push(f(l[b]));for(b=0;b<k.length;++b)showdown.helper.isUndefined(n[b])&&(n[b]=""),t.push(e(k[b],n[b]));
for(b=0;b<r.length;++b){a=[];for(c=0;c<t.length;++c)showdown.helper.isUndefined(r[b][c]),a.push(d(r[b][c],n[c]));p.push(a)}return g(t,p)});return a=b.converter._dispatch("tables.after",a,c,b)});showdown.subParser("unescapeSpecialChars",function(a){return a=a.replace(/~E(\d+)E/g,function(a,b){a=parseInt(b);return String.fromCharCode(a)})});module.exports=showdown;